default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: FavoriteBeaches_development

test:
  <<: *default
  database: FavoriteBeaches_test

production:
  <<: *default
  database: FavoriteBeaches_production
  username: FavoriteBeaches
  password: <%= ENV['FAVORITEBEACHES_DATABASE_PASSWORD'] %>
